def create_cities
	City.create(state_id:12,name: "ARTIGAS")
	City.create(state_id:12,name: "BELLA UNION")
	City.create(state_id:12,name: "TOMAS GOMENSORO")
	City.create(state_id:12,name: "BALTASAR BRUM")
	City.create(state_id:12,name: "LAS PIEDRAS")
	City.create(state_id:12,name: "PINTADITO")
	City.create(state_id:12,name: "SEQUEIRA")
	City.create(state_id:12,name: "CUAREIM")
	City.create(state_id:12,name: "BERNABE RIVERA")
	City.create(state_id:12,name: "COLONIA PALMA")
	City.create(state_id:12,name: "JAVIER DE VIANA")
	City.create(state_id:12,name: "TOPADOR")
	City.create(state_id:12,name: "CUARO")
	City.create(state_id:12,name: "BRIGADIER GENERAL DIEGO LAMAS")
	City.create(state_id:12,name: "CAMPAMENTO")
	City.create(state_id:12,name: "CATALAN GRANDE")
	City.create(state_id:12,name: "CATALAN VOLCAN")
	City.create(state_id:12,name: "CERRO DEL TIGRE")
	City.create(state_id:12,name: "COLONIA BDIER. GRAL RIVERA")
	City.create(state_id:12,name: "CUARO CHICO")
	City.create(state_id:12,name: "CHIFLERO")
	City.create(state_id:12,name: "ESTIBA")
	City.create(state_id:12,name: "FAGUNDEZ")
	City.create(state_id:12,name: "GUAYUBIRA")
	City.create(state_id:12,name: "LA BOLSA")
	City.create(state_id:12,name: "PAGUERO")
	City.create(state_id:12,name: "PASO CAMPAMENTO")
	City.create(state_id:12,name: "PASO DE LEON")
	City.create(state_id:12,name: "PASO DE RAMOS")
	City.create(state_id:12,name: "PASO FARIAS")
	City.create(state_id:12,name: "PASO POTRERO")
	City.create(state_id:12,name: "PASO RICARDINHO")
	City.create(state_id:12,name: "PATITAS")
	City.create(state_id:12,name: "PIEDRA PINTADA")
	City.create(state_id:12,name: "PINTADO GRANDE")
	City.create(state_id:12,name: "RINCON DE PACHECO")
	City.create(state_id:12,name: "SARANDI DE CUARO")
	City.create(state_id:12,name: "TAMANDUA")
	City.create(state_id:12,name: "TARUMAN")
	City.create(state_id:12,name: "TRES CERROS DE SANTIÑO")
	City.create(state_id:12,name: "URUMBEBA")
	City.create(state_id:12,name: "ZANJA ARUERA")
	City.create(state_id:2,name: "LAS PIEDRAS")
	City.create(state_id:2,name: "PANDO")
	City.create(state_id:2,name: "LA PAZ")
	City.create(state_id:2,name: "CANELONES")
	City.create(state_id:2,name: "EL PINAR")
	City.create(state_id:2,name: "SANTA LUCIA")
	City.create(state_id:2,name: "LOMAS DE SOLYMAR")
	City.create(state_id:2,name: "SOLYMAR")
	City.create(state_id:2,name: "PROGRESO")
	City.create(state_id:2,name: "Fracc Con Maldonado")
	City.create(state_id:2,name: "PASO DE CARRASCO")
	City.create(state_id:2,name: "BARROS BLANCOS")
	City.create(state_id:2,name: "Juan Antonio Artigas")
	City.create(state_id:2,name: "Villa Crespo y San Andrés")
	City.create(state_id:2,name: "COLONIA NICOLICH")
	City.create(state_id:2,name: "PARQUE CARRASCO")
	City.create(state_id:2,name: "LAGOMAR")
	City.create(state_id:2,name: "FRACC CON DEL ANDALUZ Y RUTA 84")
	City.create(state_id:2,name: "SAN RAMON")
	City.create(state_id:2,name: "SAN JOSE DE CARRASCO")
	City.create(state_id:2,name: "SALINAS")
	City.create(state_id:2,name: "JOAQUIN SUAREZ")
	City.create(state_id:2,name: "PARQUE DEL PLATA")
	City.create(state_id:2,name: "SAUCE")
	City.create(state_id:2,name: "TALA")
	City.create(state_id:2,name: "BARRA DE CARRASCO")
	City.create(state_id:2,name: "ATLANTIDA")
	City.create(state_id:2,name: "VILLA AEOROPARQUE")
	City.create(state_id:2,name: "TOLEDO")
	City.create(state_id:2,name: "EMPALME OLMOS")
	City.create(state_id:2,name: "SAN JACINTO")
	City.create(state_id:2,name: "Santa Rosa")
	City.create(state_id:2,name: "PINAMAR")
	City.create(state_id:2,name: "NEPTUNIA")
	City.create(state_id:2,name: "SHANGRILA")
	City.create(state_id:2,name: "MARINDIA")
	City.create(state_id:2,name: "COLINAS DE SOLYMAR")
	City.create(state_id:2,name: "ESTACION ATLANTIDA")
	City.create(state_id:2,name: "LAS TOSCAS")
	City.create(state_id:2,name: "MIGUES")
	City.create(state_id:2,name: "Cerrillos")
	City.create(state_id:2,name: "CERRILLOS AL SUR")
	City.create(state_id:2,name: "SAN BAUTISTA")
	City.create(state_id:2,name: "DR. FRANCISCO SOCA")
	City.create(state_id:2,name: "MONTES")
	City.create(state_id:2,name: "SAN ANTONIO")
	City.create(state_id:2,name: "FRACC RUTA 74")
	City.create(state_id:2,name: "Villa San José")
	City.create(state_id:2,name: "Juanicó")
	City.create(state_id:2,name: "Villa Felicidad")
	City.create(state_id:2,name: "SAN LUIS")
	City.create(state_id:2,name: "La Floresta Estación")
	City.create(state_id:2,name: "La Floresta")
	City.create(state_id:2,name: "AGUAS CORRIENTES")
	City.create(state_id:2,name: "El Bosque")
	City.create(state_id:2,name: "City Golf")
	City.create(state_id:2,name: "Costa Azul")
	City.create(state_id:2,name: "BARRIO COPOLA")
	City.create(state_id:2,name: "Totoral del Sauce")
	City.create(state_id:2,name: "Jardines de Pando")
	City.create(state_id:2,name: "Estanque de Pando")
	City.create(state_id:2,name: "Castellanos")
	City.create(state_id:2,name: "Costa y Guillamón")
	City.create(state_id:2,name: "Seis Hermanos")
	City.create(state_id:2,name: "Villa Argentina")
	City.create(state_id:2,name: "Barrio La Lucha")
	City.create(state_id:2,name: "Villa El Tato")
	City.create(state_id:2,name: "Villa Paz S A")
	City.create(state_id:2,name: "Olmos")
	City.create(state_id:2,name: "Viejo Molino San Bernardo")
	City.create(state_id:2,name: "Cuchilla Alta")
	City.create(state_id:2,name: "Villa Porvenir")
	City.create(state_id:2,name: "Lomas de Carrasco")
	City.create(state_id:2,name: "La Montañesa")
	City.create(state_id:2,name: "Parada Cabrera")
	City.create(state_id:2,name: "Piedra del Toro")
	City.create(state_id:2,name: "Paso Espinosa")
	City.create(state_id:2,name: "BELLO HORIZONTE")
	City.create(state_id:2,name: "Jaureguiberry")
	City.create(state_id:2,name: "Estación Tapia")
	City.create(state_id:2,name: "Instituto Adventista")
	City.create(state_id:2,name: "Santa Lucía del Este")
	City.create(state_id:2,name: "Campo Militar")
	City.create(state_id:2,name: "Aeropuerto Internacional de Carrasco")
	City.create(state_id:2,name: "Villa San Felipe")
	City.create(state_id:2,name: "Villa Hadita")
	City.create(state_id:2,name: "Fortín de Santa Rosa")
	City.create(state_id:2,name: "La Tuna")
	City.create(state_id:2,name: "Estación Migues")
	City.create(state_id:2,name: "Barrio Remanso")
	City.create(state_id:2,name: "Paso de Pache")
	City.create(state_id:2,name: "SANTA ANA")
	City.create(state_id:2,name: "Cruz de los Caminos")
	City.create(state_id:2,name: "Paso de la Cadena")
	City.create(state_id:2,name: "ARAMINDA")
	City.create(state_id:2,name: "Fracc Progreso")
	City.create(state_id:2,name: "Villa San Cono")
	City.create(state_id:2,name: "Estación Pedrera")
	City.create(state_id:2,name: "Paso Palomeque")
	City.create(state_id:2,name: "Villa Arejo")
	City.create(state_id:2,name: "Capilla de Cella")
	City.create(state_id:2,name: "El Galeón")
	City.create(state_id:2,name: "Los Titanes")
	City.create(state_id:2,name: "Bolívar")
	City.create(state_id:2,name: "Piedras de Afilar")
	City.create(state_id:2,name: "Guazú Virá")
	City.create(state_id:2,name: "Barrio Asunción")
	City.create(state_id:2,name: "Altos de la Tahona")
	City.create(state_id:2,name: "Quintas del Bosque")
	City.create(state_id:2,name: "ARGENTINO")
	City.create(state_id:2,name: "Asentamiento R6 Km 24500")
	City.create(state_id:2,name: "BIARRITZ")
	City.create(state_id:2,name: "Colinas de Carrasco")
	City.create(state_id:2,name: "Country Villa Juana")
	City.create(state_id:2,name: "Carmel")
	City.create(state_id:2,name: "BARRA DE LA PEDRERA")
	City.create(state_id:2,name: "BARRANCAS COLORADAS")
	City.create(state_id:2,name: "CAMINO A LA CADENA")
	City.create(state_id:2,name: "CANEPA Y SANTA RITA")
	City.create(state_id:2,name: "CITY PARK")
	City.create(state_id:2,name: "COSTA DE PANDO")
	City.create(state_id:2,name: "CRUZ DE LOS CAMINOS")
	City.create(state_id:2,name: "CUCHILLA VERDE")
	City.create(state_id:2,name: "CUEVA DEL TIGRE")
	City.create(state_id:2,name: "ECHEVARRIA")
	City.create(state_id:2,name: "EL COLORADO")
	City.create(state_id:2,name: "EMPALME NICOLICH")
	City.create(state_id:2,name: "EMPALME SAUCE")
	City.create(state_id:2,name: "ESTACION LA FLORESTA")
	City.create(state_id:2,name: "GUAZUVIRA")
	City.create(state_id:2,name: "JOANICO")
	City.create(state_id:2,name: "LA PALMITA")
	City.create(state_id:2,name: "LAS BRUJAS")
	City.create(state_id:2,name: "LOS TITANES")
	City.create(state_id:2,name: "PARQUE MIRAMAR")
	City.create(state_id:2,name: "PASO DE LAS TOSCAS")
	City.create(state_id:2,name: "PASO DEL BOTE")
	City.create(state_id:2,name: "PUENTE DE BRUJAS")
	City.create(state_id:2,name: "PUNTAS DE PANTANOSO")
	City.create(state_id:2,name: "RINCON DEL COLORADO")
	City.create(state_id:2,name: "SANTOS LUGARES")
	City.create(state_id:2,name: "SIERRA DEL MAR")
	City.create(state_id:2,name: "SOLIS GRANDE")
	City.create(state_id:2,name: "TAPIA")
	City.create(state_id:2,name: "VILLA INSTITUTO ADVENTISTA")
	City.create(state_id:2,name: "LOS CERRILLOS")
	City.create(state_id:2,name: "CIUDAD DE LA COSTA")
	City.create(state_id:2,name: "MEDANOS DE SOLYMAR")
	City.create(state_id:2,name: "PARQUE DE SOLYMAR")
	City.create(state_id:10,name: "Melo")
	City.create(state_id:10,name: "Río Branco")
	City.create(state_id:10,name: "Fraile Muerto")
	City.create(state_id:10,name: "Isidoro Noblía")
	City.create(state_id:10,name: "ACEGUA")
	City.create(state_id:10,name: "Tupambaé")
	City.create(state_id:10,name: "Hipódromo")
	City.create(state_id:10,name: "Plácido Rosas")
	City.create(state_id:10,name: "BARRIO LOPEZ BENITES")
	City.create(state_id:10,name: "Barrio La Vinchuca")
	City.create(state_id:10,name: "Lago Merín")
	City.create(state_id:10,name: "BAÑADO DE MEDINA")
	City.create(state_id:10,name: "Cerro de las Cuentas")
	City.create(state_id:10,name: "ARBOLITO")
	City.create(state_id:10,name: "Tres Islas")
	City.create(state_id:10,name: "Ramón Trigo")
	City.create(state_id:10,name: "Toledo")
	City.create(state_id:10,name: "La Pedrera")
	City.create(state_id:10,name: "Caserío Las Cañas")
	City.create(state_id:10,name: "AREVALO")
	City.create(state_id:10,name: "Mangrullo")
	City.create(state_id:10,name: "Soto Goro")
	City.create(state_id:10,name: "Esperanza")
	City.create(state_id:10,name: "Nando")
	City.create(state_id:10,name: "ARACHANIA")
	City.create(state_id:10,name: "AGUIRRE")
	City.create(state_id:10,name: "AMARILLO")
	City.create(state_id:10,name: "BAÑADO DE SATURNINO")
	City.create(state_id:10,name: "BUENA VISTA")
	City.create(state_id:10,name: "CALERA DE RECALDE")
	City.create(state_id:10,name: "CAMPAMENTO")
	City.create(state_id:10,name: "CAÑITAS")
	City.create(state_id:10,name: "CENTURION")
	City.create(state_id:10,name: "COIMBRA")
	City.create(state_id:10,name: "CRUZ DE PIEDRAS")
	City.create(state_id:10,name: "CUCHILLA DE MELO")
	City.create(state_id:10,name: "CUCHILLA DEL CARMEN")
	City.create(state_id:10,name: "CUCHILLA PERALTA")
	City.create(state_id:10,name: "ESCUELA DE AGRONOMIA")
	City.create(state_id:10,name: "GANEN")
	City.create(state_id:10,name: "GARAO")
	City.create(state_id:10,name: "GUAZUNAMBI")
	City.create(state_id:10,name: "LA GLORIA")
	City.create(state_id:10,name: "LAGUNA DEL JUNCO")
	City.create(state_id:10,name: "LAS LIMAS")
	City.create(state_id:10,name: "MARIA ISABEL")
	City.create(state_id:10,name: "MEDEROS")
	City.create(state_id:10,name: "MONTECITO")
	City.create(state_id:10,name: "PASO DE LAS TROPAS")
	City.create(state_id:10,name: "PASO MELO")
	City.create(state_id:10,name: "PASO PEREIRA")
	City.create(state_id:10,name: "PIEDRA ALTA")
	City.create(state_id:10,name: "PIÑEIRO")
	City.create(state_id:10,name: "PUEBLO URUGUAY")
	City.create(state_id:10,name: "PUENTE DEL CHUY")
	City.create(state_id:10,name: "PUNTAS DEL TACUARI")
	City.create(state_id:10,name: "QUEBRACHO")
	City.create(state_id:10,name: "RINCON DE CONTRERAS")
	City.create(state_id:10,name: "RINCON DE LOS CORONELES")
	City.create(state_id:10,name: "RINCON DE LOS MONTANA")
	City.create(state_id:10,name: "RINCON DE LOS OLIVERA")
	City.create(state_id:10,name: "RINCON DE PAIVA")
	City.create(state_id:10,name: "RINCON DE PY")
	City.create(state_id:10,name: "RODRIGUEZ")
	City.create(state_id:10,name: "SANCHEZ")
	City.create(state_id:10,name: "SARANDI DE ACEGUA")
	City.create(state_id:10,name: "TRES BOLICHES")
	City.create(state_id:10,name: "VILLA VIÑOLES")
	City.create(state_id:5,name: "Colonia del Sacramento")
	City.create(state_id:5,name: "Carmelo")
	City.create(state_id:5,name: "Juan Lacaze")
	City.create(state_id:5,name: "Nueva Helvecia")
	City.create(state_id:5,name: "Rosario")
	City.create(state_id:5,name: "Nueva Palmira")
	City.create(state_id:5,name: "Tarariras")
	City.create(state_id:5,name: "Florencio Sánchez")
	City.create(state_id:5,name: "Ombúes de Lavalle")
	City.create(state_id:5,name: "Colonia Valdense")
	City.create(state_id:5,name: "Miguelete")
	City.create(state_id:5,name: "Conchillas")
	City.create(state_id:5,name: "La Paz")
	City.create(state_id:5,name: "El Semillero")
	City.create(state_id:5,name: "Pastoreo")
	City.create(state_id:5,name: "Cufré")
	City.create(state_id:5,name: "Campana")
	City.create(state_id:5,name: "Radial Hernández")
	City.create(state_id:5,name: "Agraciada")
	City.create(state_id:5,name: "Estanzuela")
	City.create(state_id:5,name: "Paraje Minuano")
	City.create(state_id:5,name: "Santa Ana")
	City.create(state_id:5,name: "Riachuelo")
	City.create(state_id:5,name: "Los Pinos")
	City.create(state_id:5,name: "Playa Britópolis")
	City.create(state_id:5,name: "Paso Antolín")
	City.create(state_id:5,name: "BARKER")
	City.create(state_id:5,name: "Arrivillaga")
	City.create(state_id:5,name: "Los Cerros de San Juan")
	City.create(state_id:5,name: "Colonia Cosmopolita")
	City.create(state_id:5,name: "Chico Torino")
	City.create(state_id:5,name: "Zagarzazú")
	City.create(state_id:5,name: "Puerto Inglés")
	City.create(state_id:5,name: "Playa Fomento")
	City.create(state_id:5,name: "Blanca Arena")
	City.create(state_id:5,name: "ARTILLEROS")
	City.create(state_id:5,name: "Playa Parant")
	City.create(state_id:5,name: "Brisas del Plata")
	City.create(state_id:5,name: "Santa Regina")
	City.create(state_id:5,name: "Playa Azul")
	City.create(state_id:5,name: "BELGRANO SUR")
	City.create(state_id:5,name: "BOCA DEL ROSARIO")
	City.create(state_id:5,name: "BUENA HORA")
	City.create(state_id:5,name: "CERRO DE LAS ARMAS")
	City.create(state_id:5,name: "CERROS DE SAN JUAN")
	City.create(state_id:5,name: "COLONIA ARRUE")
	City.create(state_id:5,name: "COLONIA ESTRELLA")
	City.create(state_id:5,name: "COSTA DE NAVARRO")
	City.create(state_id:5,name: "EL CERRO")
	City.create(state_id:5,name: "El Ensueño")
	City.create(state_id:5,name: "EL GENERAL")
	City.create(state_id:5,name: "FOMENTO")
	City.create(state_id:5,name: "JUAN GONZALEZ")
	City.create(state_id:5,name: "LA CAPILLA")
	City.create(state_id:5,name: "LA ESTANZUELA")
	City.create(state_id:5,name: "MARTIN CHICO")
	City.create(state_id:5,name: "MINAS DE NARANCIO")
	City.create(state_id:5,name: "PIEDRA DE LOS INDIOS")
	City.create(state_id:5,name: "PLAYA BRITOPOLIS")
	City.create(state_id:5,name: "PUNTAS DEL ROSARIO")
	City.create(state_id:5,name: "RADIAL CONCHILLAS")
	City.create(state_id:5,name: "ROSARIO Y COLLA")
	City.create(state_id:5,name: "SAN JUAN")
	City.create(state_id:5,name: "SAN PEDRO")
	City.create(state_id:16,name: "Durazno")
	City.create(state_id:16,name: "Sarandí del Yí")
	City.create(state_id:16,name: "Carmen")
	City.create(state_id:16,name: "La Paloma")
	City.create(state_id:16,name: "Santa Bernardina")
	City.create(state_id:16,name: "Blanquillo")
	City.create(state_id:16,name: "Cerro Chato")
	City.create(state_id:16,name: "Carlos Reyles")
	City.create(state_id:16,name: "Centenario")
	City.create(state_id:16,name: "San Jorge")
	City.create(state_id:16,name: "BAYGORRIA")
	City.create(state_id:16,name: "AGUAS BUENAS")
	City.create(state_id:16,name: "Ombúes de Oribe")
	City.create(state_id:16,name: "Feliciano")
	City.create(state_id:16,name: "Rossell y Rius")
	City.create(state_id:16,name: "Pueblo de Álvarez")
	City.create(state_id:16,name: "ALVAREZ")
	City.create(state_id:16,name: "CAPILLA DE FARRUCO")
	City.create(state_id:16,name: "CERREZUELO")
	City.create(state_id:16,name: "CERRO CONVENTO")
	City.create(state_id:16,name: "CUCHILLA DE RAMIREZ")
	City.create(state_id:16,name: "LA MAZAMORRA")
	City.create(state_id:16,name: "MARIA CEJAS")
	City.create(state_id:16,name: "PALOMAS")
	City.create(state_id:16,name: "PARADA KM 265")
	City.create(state_id:16,name: "PARISH")
	City.create(state_id:16,name: "SANDU CHICO")
	City.create(state_id:16,name: "VILLA DEL CARMEN")
	City.create(state_id:19,name: "Trinidad")
	City.create(state_id:19,name: "Ismael Cortinas")
	City.create(state_id:19,name: "Andresito")
	City.create(state_id:19,name: "La Casilla")
	City.create(state_id:19,name: "Cerro Colorado")
	City.create(state_id:19,name: "Juan José Castro")
	City.create(state_id:19,name: "ANDRESITO")
	City.create(state_id:19,name: "ARENAL CHICO")
	City.create(state_id:19,name: "COLONIA ALEMANA")
	City.create(state_id:19,name: "EL TOTORAL")
	City.create(state_id:19,name: "PUEBLO PINTOS")
	City.create(state_id:19,name: "PUNTAS DE SARANDI")
	City.create(state_id:19,name: "PUNTAS DEL CORRAL DE PIEDRA")
	City.create(state_id:19,name: "PUNTAS DEL SAUCE")
	City.create(state_id:19,name: "SANTA ADELAIDA")
	City.create(state_id:14,name: "Florida")
	City.create(state_id:14,name: "Sarandí Grande")
	City.create(state_id:14,name: "Casupá")
	City.create(state_id:14,name: "Fray Marcos")
	City.create(state_id:14,name: "Veinticinco de Mayo")
	City.create(state_id:14,name: "Veinticinco de Agosto")
	City.create(state_id:14,name: "Cerro Colorado")
	City.create(state_id:14,name: "Cardal")
	City.create(state_id:14,name: "Nico Pérez")
	City.create(state_id:14,name: "Capilla del Sauce")
	City.create(state_id:14,name: "Mendoza Chico")
	City.create(state_id:14,name: "Mendoza")
	City.create(state_id:14,name: "La Cruz")
	City.create(state_id:14,name: "Chamizo")
	City.create(state_id:14,name: "Cerro Chato")
	City.create(state_id:14,name: "Independencia")
	City.create(state_id:14,name: "Reboledo")
	City.create(state_id:14,name: "Goñi")
	City.create(state_id:14,name: "BERRONDO")
	City.create(state_id:14,name: "Puntas de Maciel")
	City.create(state_id:14,name: "Pintado")
	City.create(state_id:14,name: "La Macana")
	City.create(state_id:14,name: "Montecoral")
	City.create(state_id:14,name: "Polanco del Yí")
	City.create(state_id:14,name: "Illescas")
	City.create(state_id:14,name: "Estación Capilla del Sauce")
	City.create(state_id:14,name: "Valentines")
	City.create(state_id:14,name: "Caserío La Fundación")
	City.create(state_id:14,name: "Pueblo Ferrer")
	City.create(state_id:14,name: "ARRAYAN")
	City.create(state_id:14,name: "CHINGOLAS")
	City.create(state_id:14,name: "DR ALEJANDRO GALLINAL")
	City.create(state_id:14,name: "FERRER")
	City.create(state_id:14,name: "HERNANDARIAS")
	City.create(state_id:14,name: "JUNCAL")
	City.create(state_id:14,name: "MOLLES DEL PESCADO")
	City.create(state_id:14,name: "PALERMO")
	City.create(state_id:14,name: "PASO DE LOS NOVILLOS")
	City.create(state_id:14,name: "PUEBLO DE LOS MOROCHOS")
	City.create(state_id:14,name: "PUNTAS DE MANSAVILLAGRA")
	City.create(state_id:14,name: "TALITA")
	City.create(state_id:14,name: "VILLA VIEJA")
	City.create(state_id:14,name: "25 DE AGOSTO")
	City.create(state_id:14,name: "25 DE MAYO")
	City.create(state_id:14,name: "ALEJANDRO GALLINAL")
	City.create(state_id:15,name: "Minas")
	City.create(state_id:15,name: "José Pedro Varela")
	City.create(state_id:15,name: "Solís de Mataojo")
	City.create(state_id:15,name: "José Batlle y Ordóñez")
	City.create(state_id:15,name: "Mariscala")
	City.create(state_id:15,name: "Pirarajá")
	City.create(state_id:15,name: "Zapicán")
	City.create(state_id:15,name: "BARRIO LA CORONILLA ANCAP")
	City.create(state_id:15,name: "Colón")
	City.create(state_id:15,name: "Campanero")
	City.create(state_id:15,name: "Poblado Aramendía")
	City.create(state_id:15,name: "Villa del Rosario")
	City.create(state_id:15,name: "Polanco Norte")
	City.create(state_id:15,name: "Villa Serrana")
	City.create(state_id:15,name: "Pueblo 19 de Junio")
	City.create(state_id:15,name: "Estación Solís")
	City.create(state_id:15,name: "Illescas")
	City.create(state_id:15,name: "ALONSO")
	City.create(state_id:15,name: "AZUCAR")
	City.create(state_id:15,name: "CARNALES")
	City.create(state_id:15,name: "COSTAS DEL SOLDADO")
	City.create(state_id:15,name: "DIECINUEVE DE JUNIO")
	City.create(state_id:15,name: "EL SOLDADO")
	City.create(state_id:15,name: "GODOY")
	City.create(state_id:15,name: "HIGUERITAS")
	City.create(state_id:15,name: "LA PLATA")
	City.create(state_id:15,name: "LADRILLOS")
	City.create(state_id:15,name: "LAS ACHIRAS")
	City.create(state_id:15,name: "LUIS ANDREONI")
	City.create(state_id:15,name: "MARCO DE LOS REYES")
	City.create(state_id:15,name: "MOLLES DE CAÑADA GRANDE")
	City.create(state_id:15,name: "ORTIZ")
	City.create(state_id:15,name: "PEDRO ARAMENDIA")
	City.create(state_id:15,name: "POLANCO SUR")
	City.create(state_id:15,name: "POLANCOS")
	City.create(state_id:15,name: "PUNTAS DE SANTA LUCIA")
	City.create(state_id:15,name: "RETAMOSA")
	City.create(state_id:15,name: "RINCON DE CEBOLLATI")
	City.create(state_id:15,name: "RINCON DE MARISCALA")
	City.create(state_id:15,name: "SARANDI DE GUTIERREZ")
	City.create(state_id:15,name: "TAPES CHICO")
	City.create(state_id:15,name: "TAPES GRANDE")
	City.create(state_id:15,name: "VELAZQUEZ")
	City.create(state_id:3,name: "Maldonado")
	City.create(state_id:3,name: "San Carlos")
	City.create(state_id:3,name: "Pinares Las Delicias")
	City.create(state_id:3,name: "Piriápolis")
	City.create(state_id:3,name: "Punta del Este")
	City.create(state_id:3,name: "Pan de Azúcar")
	City.create(state_id:3,name: "Cerro Pelado")
	City.create(state_id:3,name: "AIGUA")
	City.create(state_id:3,name: "San Rafael El Placer")
	City.create(state_id:3,name: "BARRIO HIPODROMO")
	City.create(state_id:3,name: "La Sonrisa")
	City.create(state_id:3,name: "Gregorio Aznárez")
	City.create(state_id:3,name: "El Tesoro")
	City.create(state_id:3,name: "Playa Grande")
	City.create(state_id:3,name: "Barrio Los Aromos")
	City.create(state_id:3,name: "Villa Delia")
	City.create(state_id:3,name: "Balneario Buenos Aires")
	City.create(state_id:3,name: "Gerona")
	City.create(state_id:3,name: "La Capuera")
	City.create(state_id:3,name: "Las Flores Estación")
	City.create(state_id:3,name: "Playa Hermosa")
	City.create(state_id:3,name: "Punta Ballena")
	City.create(state_id:3,name: "La Barra")
	City.create(state_id:3,name: "Solís")
	City.create(state_id:3,name: "Cerros Azules")
	City.create(state_id:3,name: "El Chorro")
	City.create(state_id:3,name: "Playa Verde")
	City.create(state_id:3,name: "Las Flores")
	City.create(state_id:3,name: "Garzón")
	City.create(state_id:3,name: "Manantiales")
	City.create(state_id:3,name: "Faro José Ignacio")
	City.create(state_id:3,name: "Canteras de Marelli")
	City.create(state_id:3,name: "Bella Vista")
	City.create(state_id:3,name: "Parque Medina")
	City.create(state_id:3,name: "Los Talas")
	City.create(state_id:3,name: "Ruta 37 y 9")
	City.create(state_id:3,name: "Nueva Carrara")
	City.create(state_id:3,name: "Ocean Park")
	City.create(state_id:3,name: "Sauce de Portezuelo")
	City.create(state_id:3,name: "Punta Colorada")
	City.create(state_id:3,name: "Santa Mónica")
	City.create(state_id:3,name: "Los Corchos")
	City.create(state_id:3,name: "Punta Negra")
	City.create(state_id:3,name: "El Edén")
	City.create(state_id:3,name: "Edén Rock")
	City.create(state_id:3,name: "Chihuahua")
	City.create(state_id:3,name: "Las Cumbres")
	City.create(state_id:3,name: "ARENAS DE JOSE IGNACIO")
	City.create(state_id:3,name: "ABRA DE CASTELLANOS")
	City.create(state_id:3,name: "BUENOS AIRES")
	City.create(state_id:3,name: "EL EDEN")
	City.create(state_id:3,name: "EL PLACER")
	City.create(state_id:3,name: "GUARDIA VIEJA")
	City.create(state_id:3,name: "JOSE IGNACIO")
	City.create(state_id:3,name: "LAS DELICIAS PINARES")
	City.create(state_id:3,name: "LOS CEIBOS")
	City.create(state_id:3,name: "PASO DE LOS TALAS")
	City.create(state_id:3,name: "PORTEZUELO")
	City.create(state_id:3,name: "PUNTAS DE JOSE IGNACIO")
	City.create(state_id:3,name: "SALAMANCA")
	City.create(state_id:3,name: "SAUCE DE AIGUA")
	City.create(state_id:3,name: "SOLIS GRANDE")
	City.create(state_id:3,name: "CERRO PELADO")
	City.create(state_id:1,name: "Montevideo")
	City.create(state_id:1,name: "Pajas Blancas")
	City.create(state_id:1,name: "Santiago Vázquez")
	City.create(state_id:1,name: "ABAYUBA")
	City.create(state_id:6,name: "Paysandú")
	City.create(state_id:6,name: "Nuevo Paysandú")
	City.create(state_id:6,name: "Chacras de Paysandú")
	City.create(state_id:6,name: "Guichón")
	City.create(state_id:6,name: "Quebracho")
	City.create(state_id:6,name: "Tambores")
	City.create(state_id:6,name: "San Félix")
	City.create(state_id:6,name: "Piedras Coloradas")
	City.create(state_id:6,name: "Porvenir")
	City.create(state_id:6,name: "Lorenzo Geyres")
	City.create(state_id:6,name: "Gallinal")
	City.create(state_id:6,name: "Chapicuy")
	City.create(state_id:6,name: "Merinos")
	City.create(state_id:6,name: "Orgoroso")
	City.create(state_id:6,name: "El Eucaliptus")
	City.create(state_id:6,name: "Casablanca")
	City.create(state_id:6,name: "BEISSO")
	City.create(state_id:6,name: "Cerro Chato")
	City.create(state_id:6,name: "Morató")
	City.create(state_id:6,name: "Constancia")
	City.create(state_id:6,name: "Cañada del Pueblo")
	City.create(state_id:6,name: "Estación Porvenir")
	City.create(state_id:6,name: "La Tentación")
	City.create(state_id:6,name: "Esperanza")
	City.create(state_id:6,name: "ARBOLITO")
	City.create(state_id:6,name: "Piñera")
	City.create(state_id:6,name: "Piedra Sola")
	City.create(state_id:6,name: "Queguayar")
	City.create(state_id:6,name: "Villa María")
	City.create(state_id:6,name: "BELLA VISTA")
	City.create(state_id:6,name: "Puntas de Arroyo Negro")
	City.create(state_id:6,name: "Pueblo Federación")
	City.create(state_id:6,name: "Cuchilla de Fuego")
	City.create(state_id:6,name: "Pueblo Alonzo")
	City.create(state_id:6,name: "ALONSO")
	City.create(state_id:6,name: "ARAUJO")
	City.create(state_id:6,name: "FEDERACION")
	City.create(state_id:6,name: "LAS FLORES")
	City.create(state_id:6,name: "QUEGUAY CHICO")
	City.create(state_id:6,name: "TIATUCURA")
	City.create(state_id:17,name: "Fray Bentos")
	City.create(state_id:17,name: "Young")
	City.create(state_id:17,name: "Nuevo Berlín")
	City.create(state_id:17,name: "San Javier")
	City.create(state_id:17,name: "Barrio Anglo")
	City.create(state_id:17,name: "ALGORTA")
	City.create(state_id:17,name: "Grecco")
	City.create(state_id:17,name: "Paso de los Mellizos")
	City.create(state_id:17,name: "Villa General Borges")
	City.create(state_id:17,name: "Sarandí de Navarro")
	City.create(state_id:17,name: "Bellaco")
	City.create(state_id:17,name: "Los Arrayanes")
	City.create(state_id:17,name: "Villa María")
	City.create(state_id:17,name: "Menafra")
	City.create(state_id:17,name: "Tres Quintas")
	City.create(state_id:17,name: "Las Cañas")
	City.create(state_id:17,name: "Merinos")
	City.create(state_id:17,name: "EL OMBU")
	City.create(state_id:17,name: "ISLAS DE ARGÜELLES")
	City.create(state_id:17,name: "LA ARENA")
	City.create(state_id:17,name: "LA CORONILLA")
	City.create(state_id:17,name: "LOS MELLIZOS")
	City.create(state_id:17,name: "PALMAR GRANDE")
	City.create(state_id:17,name: "PASO DE SOCA")
	City.create(state_id:17,name: "ROLON")
	City.create(state_id:17,name: "SANTA ROSA")
	City.create(state_id:17,name: "SAUCE")
	City.create(state_id:8,name: "Rivera")
	City.create(state_id:8,name: "Tranqueras")
	City.create(state_id:8,name: "Mandubí")
	City.create(state_id:8,name: "Vichadero")
	City.create(state_id:8,name: "Minas de Corrales")
	City.create(state_id:8,name: "La Pedrera")
	City.create(state_id:8,name: "Santa Teresa")
	City.create(state_id:8,name: "Lagunón")
	City.create(state_id:8,name: "Lapuente")
	City.create(state_id:8,name: "Paso Hospital")
	City.create(state_id:8,name: "Masoller")
	City.create(state_id:8,name: "Lagos del Norte")
	City.create(state_id:8,name: "Moirones")
	City.create(state_id:8,name: "Cerro Pelado")
	City.create(state_id:8,name: "Cerros de la Calera")
	City.create(state_id:8,name: "Cerrillada")
	City.create(state_id:8,name: "Las Flores")
	City.create(state_id:8,name: "ARROYO BLANCO")
	City.create(state_id:8,name: "Amarillo")
	City.create(state_id:8,name: "ABROJAL")
	City.create(state_id:8,name: "ALBORADA")
	City.create(state_id:8,name: "ATAQUES")
	City.create(state_id:8,name: "BARRIO LAGUNON")
	City.create(state_id:8,name: "BARRIO PEREIRA")
	City.create(state_id:8,name: "BATOVI")
	City.create(state_id:8,name: "BERRUTI")
	City.create(state_id:8,name: "BLANQUILLOS")
	City.create(state_id:8,name: "CAPON ALTO")
	City.create(state_id:8,name: "CERRILLADA")
	City.create(state_id:8,name: "CERRO PELADO DEL ESTE")
	City.create(state_id:8,name: "CORONILLA")
	City.create(state_id:8,name: "CORONILLA DE CORRALES")
	City.create(state_id:8,name: "CUCHILLA MANGUERAS")
	City.create(state_id:8,name: "CURTUME")
	City.create(state_id:8,name: "CHIRCA DE CARAGUATA")
	City.create(state_id:8,name: "GUAVIYU")
	City.create(state_id:8,name: "HOSPITAL")
	City.create(state_id:8,name: "LAPUENTE")
	City.create(state_id:8,name: "MINAS DE ZAPUCAY")
	City.create(state_id:8,name: "PASO DE AMARILLO")
	City.create(state_id:8,name: "PASO DE ATAQUES")
	City.create(state_id:8,name: "PASO DEL PARQUE")
	City.create(state_id:8,name: "PUNTAS DE ABROJAL")
	City.create(state_id:8,name: "PUNTAS DE CORRALES")
	City.create(state_id:8,name: "VILLA INDART")
	City.create(state_id:8,name: "YAGUARI")
	City.create(state_id:13,name: "Rocha")
	City.create(state_id:13,name: "Chuy")
	City.create(state_id:13,name: "Castillos")
	City.create(state_id:13,name: "Lascano")
	City.create(state_id:13,name: "La Paloma")
	City.create(state_id:13,name: "Cebollatí")
	City.create(state_id:13,name: "19 DE ABRIL")
	City.create(state_id:13,name: "La Aguada Costa Azul")
	City.create(state_id:13,name: "Velázquez")
	City.create(state_id:13,name: "San Luis al Medio")
	City.create(state_id:13,name: "La Coronilla")
	City.create(state_id:13,name: "Puimayen")
	City.create(state_id:13,name: "Capacho")
	City.create(state_id:13,name: "AGUAS DULCES")
	City.create(state_id:13,name: "Punta del Diablo")
	City.create(state_id:13,name: "BARRA DEL CHUY")
	City.create(state_id:13,name: "BARRA DE VALIZAS")
	City.create(state_id:13,name: "ARACHANIA")
	City.create(state_id:13,name: "Diecinueve de Abril")
	City.create(state_id:13,name: "Barrio Pereira")
	City.create(state_id:13,name: "La Pedrera")
	City.create(state_id:13,name: "Cabo Polonio")
	City.create(state_id:13,name: "BARRIO TORRES")
	City.create(state_id:13,name: "La Esmeralda")
	City.create(state_id:13,name: "La Riviera")
	City.create(state_id:13,name: "Parallé")
	City.create(state_id:13,name: "Pta Rubia y Sta.Isabel de la Pedrera")
	City.create(state_id:13,name: "Puerto de los Botes")
	City.create(state_id:13,name: "Palmares de la Coronilla")
	City.create(state_id:13,name: "ANTONIOPOLIS")
	City.create(state_id:13,name: "ARROZAL VICTORIA")
	City.create(state_id:13,name: "BUENA VISTA")
	City.create(state_id:13,name: "CERRO DE LOS ROCHA")
	City.create(state_id:13,name: "CUCHILLA DE GARZON")
	City.create(state_id:13,name: "EL CANELON")
	City.create(state_id:13,name: "EL CARACOL")
	City.create(state_id:13,name: "EL CHIMANGO")
	City.create(state_id:13,name: "FONDO DE VALIZAS")
	City.create(state_id:13,name: "LAGUNITAS")
	City.create(state_id:13,name: "LAS GARZAS")
	City.create(state_id:13,name: "LOS TACURUCES")
	City.create(state_id:13,name: "PALMAR")
	City.create(state_id:13,name: "PASO BARRANCAS")
	City.create(state_id:13,name: "PASO DEL BAÑADO")
	City.create(state_id:13,name: "PICADA TOLOSA")
	City.create(state_id:13,name: "POBLADO CORREA")
	City.create(state_id:13,name: "QUEBRACHO")
	City.create(state_id:13,name: "RINCON DE LOS OIVERA")
	City.create(state_id:13,name: "VUELTA DEL PALMAR")
	City.create(state_id:13,name: "18 DE JULIO")
	City.create(state_id:4,name: "Salto")
	City.create(state_id:4,name: "Constitución")
	City.create(state_id:4,name: "BELEN")
	City.create(state_id:4,name: "Pueblo Lavalleja")
	City.create(state_id:4,name: "San Antonio")
	City.create(state_id:4,name: "Colonia 18 de Julio")
	City.create(state_id:4,name: "Rincón de Valentín")
	City.create(state_id:4,name: "ALBISU")
	City.create(state_id:4,name: "Colonia Itapebí")
	City.create(state_id:4,name: "BIASSINI")
	City.create(state_id:4,name: "Termas del Daymán")
	City.create(state_id:4,name: "Saucedo")
	City.create(state_id:4,name: "Garibaldi")
	City.create(state_id:4,name: "Fernández")
	City.create(state_id:4,name: "Termas del Arapey")
	City.create(state_id:4,name: "Sarandí del Arapey")
	City.create(state_id:4,name: "ARENITAS BLANCAS")
	City.create(state_id:4,name: "Puntas de Valentín")
	City.create(state_id:4,name: "Chacras de Belén")
	City.create(state_id:4,name: "Laureles")
	City.create(state_id:4,name: "Cuchilla de Guaviyú")
	City.create(state_id:4,name: "Palomas")
	City.create(state_id:4,name: "Cerros de Vera")
	City.create(state_id:4,name: "Pueblo Cayetano")
	City.create(state_id:4,name: "Celeste")
	City.create(state_id:4,name: "Paso Cementerio")
	City.create(state_id:4,name: "Guaviyú de Arapey")
	City.create(state_id:4,name: "Pueblo Russo")
	City.create(state_id:4,name: "Parque José Luis")
	City.create(state_id:4,name: "BARRIO ARTIGAS")
	City.create(state_id:4,name: "BORDENAVE")
	City.create(state_id:4,name: "CARUMBE")
	City.create(state_id:4,name: "CAYETANO")
	City.create(state_id:4,name: "CERRO CHATO")
	City.create(state_id:4,name: "FERREIRA")
	City.create(state_id:4,name: "LA BOLSA")
	City.create(state_id:4,name: "LA BOLSA 2")
	City.create(state_id:4,name: "LAS FLORES")
	City.create(state_id:4,name: "LLUVERAS")
	City.create(state_id:4,name: "OLIVERA")
	City.create(state_id:4,name: "P. FERNANDEZ")
	City.create(state_id:4,name: "PASO DE LAS CAÑAS")
	City.create(state_id:4,name: "PASO DEL PARQUE DAYMAN")
	City.create(state_id:4,name: "PASO DEL POTRERO")
	City.create(state_id:4,name: "PASO NUEVO DEL ARAPEY")
	City.create(state_id:4,name: "PEPE NUÑEZ")
	City.create(state_id:4,name: "PUEBLO FERNANDEZ")
	City.create(state_id:4,name: "QUINTANA")
	City.create(state_id:4,name: "SARANDI DE ARAPEY")
	City.create(state_id:4,name: "TORO NEGRO")
	City.create(state_id:4,name: "VALENTIN GRANDE")
	City.create(state_id:4,name: "LAVALLEJA")
	City.create(state_id:7,name: "San José de Mayo")
	City.create(state_id:7,name: "Delta del Tigre y Villas")
	City.create(state_id:7,name: "Libertad")
	City.create(state_id:7,name: "Playa Pascual")
	City.create(state_id:7,name: "Rodríguez")
	City.create(state_id:7,name: "Ecilda Paullier")
	City.create(state_id:7,name: "Santa Mónica")
	City.create(state_id:7,name: "Puntas de Valdez")
	City.create(state_id:7,name: "Rafael Perazza")
	City.create(state_id:7,name: "Monte Grande")
	City.create(state_id:7,name: "Safici")
	City.create(state_id:7,name: "Ituzaingó")
	City.create(state_id:7,name: "Raigón")
	City.create(state_id:7,name: "Capurro")
	City.create(state_id:7,name: "Villa María")
	City.create(state_id:7,name: "18 DE JULIO")
	City.create(state_id:7,name: "Mal Abrigo")
	City.create(state_id:7,name: "Juan Soler")
	City.create(state_id:7,name: "Kiyú Ordeig")
	City.create(state_id:7,name: "González")
	City.create(state_id:7,name: "Radial")
	City.create(state_id:7,name: "Cololó Tinosa")
	City.create(state_id:7,name: "Rincón del Pino")
	City.create(state_id:7,name: "Scavino")
	City.create(state_id:7,name: "Costas de Pereira")
	City.create(state_id:7,name: "Cerámicas del Sur")
	City.create(state_id:7,name: "Mangrullo Pueblo Leoncio Rivero")
	City.create(state_id:7,name: "Cañada Grande")
	City.create(state_id:7,name: "Carreta Quemada")
	City.create(state_id:7,name: "La Boyada")
	City.create(state_id:7,name: "San Gregorio")
	City.create(state_id:7,name: "Bocas del Cufré")
	City.create(state_id:7,name: "ARROYO LLANO")
	City.create(state_id:7,name: "CNEL. ADRIAN MEDINA")
	City.create(state_id:7,name: "LA CUCHILLA")
	City.create(state_id:7,name: "LA RADIAL")
	City.create(state_id:7,name: "PENINO")
	City.create(state_id:7,name: "PUNTAS DE CAÑADA GRANDE")
	City.create(state_id:7,name: "RADIAL RUTA 3")
	City.create(state_id:7,name: "RINCON DE BUSCHENTAL")
	City.create(state_id:7,name: "RINCON DE NAZARETH")
	City.create(state_id:7,name: "TROPAS VIEJAS")
	City.create(state_id:7,name: "VALDEZ CHICO")
	City.create(state_id:7,name: "VILLA RIVES")
	City.create(state_id:7,name: "CIUDAD DEL PLATA")
	City.create(state_id:11,name: "Mercedes")
	City.create(state_id:11,name: "Dolores")
	City.create(state_id:11,name: "Cardona")
	City.create(state_id:11,name: "Chacras de Dolores")
	City.create(state_id:11,name: "José Enrique Rodó")
	City.create(state_id:11,name: "Palmitas")
	City.create(state_id:11,name: "Villa de Soriano")
	City.create(state_id:11,name: "Santa Catalina")
	City.create(state_id:11,name: "Egaña")
	City.create(state_id:11,name: "Risso")
	City.create(state_id:11,name: "Villa Darwin")
	City.create(state_id:11,name: "Palmar")
	City.create(state_id:11,name: "Cañada Nieto")
	City.create(state_id:11,name: "Agraciada")
	City.create(state_id:11,name: "Palo Solo")
	City.create(state_id:11,name: "Pueblo Castillos")
	City.create(state_id:11,name: "Perseverano")
	City.create(state_id:11,name: "La Loma")
	City.create(state_id:11,name: "El Tala")
	City.create(state_id:11,name: "La Concordia")
	City.create(state_id:11,name: "Colonia Concordia")
	City.create(state_id:11,name: "LARES")
	City.create(state_id:11,name: "AGRACIADA")
	City.create(state_id:11,name: "VILLA SORIANO")
	City.create(state_id:9,name: "Tacuarembó")
	City.create(state_id:9,name: "Paso de los Toros")
	City.create(state_id:9,name: "San Gregorio de Polanco")
	City.create(state_id:9,name: "ANSINA")
	City.create(state_id:9,name: "Curtina")
	City.create(state_id:9,name: "Las Toscas")
	City.create(state_id:9,name: "ACHAR")
	City.create(state_id:9,name: "Tambores")
	City.create(state_id:9,name: "Paso Bonilla")
	City.create(state_id:9,name: "Paso del Cerro")
	City.create(state_id:9,name: "Cuchilla de Peralta")
	City.create(state_id:9,name: "La Pedrera")
	City.create(state_id:9,name: "Clara")
	City.create(state_id:9,name: "Cuchilla del Ombú")
	City.create(state_id:9,name: "Pueblo del Barro")
	City.create(state_id:9,name: "Balneario Iporá")
	City.create(state_id:9,name: "Piedra Sola")
	City.create(state_id:9,name: "Rincón del Bonete")
	City.create(state_id:9,name: "Sauce de Batoví")
	City.create(state_id:9,name: "Chamberlain")
	City.create(state_id:9,name: "Puntas de Cinco Sauces")
	City.create(state_id:9,name: "Cardozo")
	City.create(state_id:9,name: "Laureles")
	City.create(state_id:9,name: "Cerro de Pastoreo")
	City.create(state_id:9,name: "Rincón de Pereira")
	City.create(state_id:9,name: "La Hilera")
	City.create(state_id:9,name: "ABROJAL")
	City.create(state_id:9,name: "CARAGUATA AL NORTE")
	City.create(state_id:9,name: "CARDOZO CHICO")
	City.create(state_id:9,name: "CLAVIJO")
	City.create(state_id:9,name: "CUCHILLA CARAGUATA")
	City.create(state_id:9,name: "LA BOLSA 02")
	City.create(state_id:9,name: "LA HUMEDAD")
	City.create(state_id:9,name: "LARRAYOS")
	City.create(state_id:9,name: "LAS ARENAS")
	City.create(state_id:9,name: "LAS CHILCAS")
	City.create(state_id:9,name: "LAURA")
	City.create(state_id:9,name: "LOS FEOS")
	City.create(state_id:9,name: "LOS GARCIA")
	City.create(state_id:9,name: "LOS GOMEZ")
	City.create(state_id:9,name: "LOS ORTICES")
	City.create(state_id:9,name: "LOS RODRIGUEZ")
	City.create(state_id:9,name: "LOS ROSANOS")
	City.create(state_id:9,name: "LOS ROSAS")
	City.create(state_id:9,name: "LOS VAZQUEZ")
	City.create(state_id:9,name: "MINUANO")
	City.create(state_id:9,name: "MONTEVIDEO CHICO")
	City.create(state_id:9,name: "PASO DE LOS NOVILLOS")
	City.create(state_id:9,name: "PERALTA")
	City.create(state_id:9,name: "PICADA DE CUELLO")
	City.create(state_id:9,name: "PUEBLO DE ARRIBA")
	City.create(state_id:9,name: "RINCON DE FREITAS")
	City.create(state_id:9,name: "SARANDI DE RIO NEGRO")
	City.create(state_id:9,name: "TRES GUITARRAS")
	City.create(state_id:9,name: "TURUPI")
	City.create(state_id:9,name: "VALLE EDEN")
	City.create(state_id:9,name: "ZAPUCAY")
	City.create(state_id:18,name: "Treinta y Tres")
	City.create(state_id:18,name: "Ejido de Treinta y Tres")
	City.create(state_id:18,name: "Vergara")
	City.create(state_id:18,name: "Santa Clara de Olimar")
	City.create(state_id:18,name: "Cerro Chato")
	City.create(state_id:18,name: "Gral. Enrique Martínez")
	City.create(state_id:18,name: "Estación Rincón")
	City.create(state_id:18,name: "ARROZAL TREINTA Y TRES")
	City.create(state_id:18,name: "Isla Patrulla")
	City.create(state_id:18,name: "Valentines")
	City.create(state_id:18,name: "Mendizábal")
	City.create(state_id:18,name: "María Albina")
	City.create(state_id:18,name: "Villa Passano")
	City.create(state_id:18,name: "Puntas del Parao")
	City.create(state_id:18,name: "El Bellaco")
	City.create(state_id:18,name: "Poblado Alonzo")
	City.create(state_id:18,name: "ACOSTA")
	City.create(state_id:18,name: "ARROZAL SANTA MARIA")
	City.create(state_id:18,name: "BAÑADO DE LOS OLIVERA")
	City.create(state_id:18,name: "CERROS DE AMARO")
	City.create(state_id:18,name: "CIPA OLIMAR")
	City.create(state_id:18,name: "CIPA SECADOR")
	City.create(state_id:18,name: "CIPA-CEBOLLATI")
	City.create(state_id:18,name: "CUCHILLA DE DIONISIO")
	City.create(state_id:18,name: "JULIO MARIA SANZ")
	City.create(state_id:18,name: "LA LATA")
	City.create(state_id:18,name: "LOS CEIBOS")
	City.create(state_id:18,name: "MARIA ALBINA")
	City.create(state_id:18,name: "MARIA ISABEL")
	City.create(state_id:18,name: "PASO DE PIRIZ")
	City.create(state_id:18,name: "RINCON DE GADEA")
	City.create(state_id:18,name: "RINCON DE LOS FRANCOS")
	City.create(state_id:18,name: "SIERRA DEL YERBAL")
	City.create(state_id:18,name: "SIETE CASAS")
	City.create(state_id:18,name: "TRES BOCAS")
	City.create(state_id:18,name: "LAS CHACRAS")
end